version: '3'
services:
  app-express:
    container_name: container1
    build: 
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    command: npm run start-dev