version: '3'
services:
  app-express:
    container_name: container1
    build: 
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    command: npm run start-dev
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-express


volumes:
  mongo-db: